### ISSUE TITLE
Accuracy of the model and unable to run on GPU?

### ISSUE THREAD

**Issue by Sammy-iiitb** [AnesBenmerzoug/Handwriting-Model#1]
While running the code it returns the a plot and then is not very accurate. Can I know the accuracy that you got while training your model. I am also unable to run this code on GPU even after marking the use GPU flag to True in parameter.yaml file after making the changes required for tensors to be cuda tensor.

**Comment by AnesBenmerzoug** [comment]
I am really sorry, I haven't noticed this issue before.

This is mostly a work-in-progress. I am currently trying to finish, but it turned out more difficult than expected.
